apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ue5-game-files-s3-pvc
  namespace: game
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: ue5-game-files-s3-pv