apiVersion: v1
kind: Service
metadata:
  name: ue5-gameserver
  namespace: game
spec:
  type: NodePort
  selector:
    app: ue5-server
  ports:
  - name: game
    port: 7777
    targetPort: 7777
    nodePort: 30777
    protocol: UDP
  - name: query
    port: 27015
    targetPort: 27015
    nodePort: 30015
    protocol: UDP