apiVersion: v1
kind: Secret
metadata:
  name: rclone-secret
  namespace: kube-system
type: Opaque
stringData:
  remote: "r2"
  remotePath: "k8s/LinuxServer"
  configData: |
    [r2]
    type = s3
    provider = Cloudflare
    access_key_id = 
    secret_access_key = 
    endpoint = 
    acl = private